name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: k01066624566/attendance
          stage: main
          yaml: |
            name: spring-attandance-practice
            app: java@17
            options:
              ports: 8080
              env:
                - name: REDIS_HOST
                  var: REDIS_HOST
                - name: REDIS_PORT
                  var: REDIS_PORT
                - name: JWT_ACCESS_SECRET
                  var: JWT_ACCESS_SECRET
                - name: JWT_REFRESH_SECRET
                  var: JWT_REFRESH_SECRET
                - name: DB_URL
                  var: DB_URL
                - name: DB_USER_NAME
                  var: DB_USER_NAME
                - name: DB_PASSWORD
                  var: DB_USER_PASSWORD
                - name: CLIENT_ID
                  var: CLIENT_ID
                - name: CLIENT_SECRET
                  var: CLIENT_SECRET
                - name: REDIRECT_URI
                  var: REDIRECT_URI
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
